// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvtumcrjnfwqofmpyued.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2dHVtY3JqbmZ3cW9mbXB5dWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODQ0MTgsImV4cCI6MjA3MzY2MDQxOH0.ZTUszCyFfwx2YNz5ZmO7XPlOWEONMMrkZ3lMRqRSqp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});