// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yomqllxkvuwzcskyjesj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvbXFsbHhrdnV3emNza3lqZXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTcxNzcsImV4cCI6MjA2OTc5MzE3N30.KahZ_pyxo9JBo0LIqJPve9z4Bx1YjCLHS8HB0nUJLwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});